import sqlite3
import os
from agent.state import AgentState
from langchain_openrouter import ChatOpenRouter
from dotenv import load_dotenv
load_dotenv()
import streamlit as st

# Define a constant for maximum retries until correct sql query is generated.
MAX_RETRIES = 3 

#def get_llm():
    #return ChatGoogleGenerativeAI(
       # model="gemini-2.0-flash",
  #      temperature=0
 #   )

def get_llm():
    api_key = os.getenv("OPENROUTER_API_KEY") or st.secrets.get("OPENROUTER_API_KEY")
    return ChatOpenRouter(
        model="anthropic/claude-sonnet-4-5",
        temperature=0,
        openrouter_api_key=api_key
    )

#function to log that the schema is ready and passes state along.
# ── Node 1: Schema Inspector ──────────────────────────────────────────────────
def schema_inspector_node(state: AgentState) -> AgentState:
    state["steps_log"].append("🔍 Inspecting database schema...")
    state["steps_log"].append("✅ Schema loaded successfully.")
    return state


# This node takes the current state, generates a SQL query using the LLM based on the user's question and the database schema, 
# and updates the state with the generated SQL query. It also handles retry logic if there are errors in the generated SQL.
# ── Node 2: SQL Writer ────────────────────────────────────────────────────────
def sql_writer_node(state: AgentState) -> AgentState:
    retry = state["retry_count"]
    if retry == 0:
        state["steps_log"].append("✍️ Writing SQL query...")
    else:
        state["steps_log"].append(f"🔄 Rewriting SQL (attempt {retry + 1}/{MAX_RETRIES})...")

    llm = get_llm()

    retry_context = ""
    if state.get("sql_error") or state.get("sql_query"):
        retry_context = f"""
Previous SQL attempt:
{state.get('sql_query', '')}

Error or issue: {state.get('sql_error') or state.get('validation_status')}
Please fix the above issue in your new query.
"""

    prompt = f"""You are an expert SQL analyst. Given the database schema below, write a SQLite SQL query to answer the user's question.

DATABASE SCHEMA:
{state['schema_info']}

USER QUESTION:
{state['user_question']}

{retry_context}

Rules:
- Write only valid SQLite SQL
- Use exact table and column names from the schema
- For large tables, add LIMIT 100 unless the question asks for aggregates
- Return ONLY the raw SQL query, no explanation, no markdown backticks
"""

    response = llm.invoke(prompt)
    sql = response.content.strip().replace("```sql", "").replace("```", "").strip()
    state["sql_query"] = sql
    state["sql_error"] = None
    return state

# This node executes the SQL query generated by the previous node against the SQLite database 
# and updates the state with the results or any errors encountered.
# ── Node 3: SQL Executor ──────────────────────────────────────────────────────
def sql_executor_node(state: AgentState, conn: sqlite3.Connection) -> AgentState:
    state["steps_log"].append("⚙️ Executing SQL query...")
    try:
        import pandas as pd
        df = pd.read_sql_query(state["sql_query"], conn)
        state["sql_result"] = df.to_string(index=False, max_rows=50)
        state["sql_error"] = None
        state["steps_log"].append(f"✅ Query returned {len(df)} rows.")
    except Exception as e:
        state["sql_error"] = str(e)
        state["sql_result"] = None
        state["steps_log"].append(f"❌ SQL error: {str(e)}")
    return state

# This node validates whether the SQL query result correctly answers the user's question. 
# It checks for SQL errors, empty results, and also uses the LLM to assess if the result seems correct based on the question and schema.
# ── Node 4: Result Validator ──────────────────────────────────────────────────
def result_validator_node(state: AgentState) -> AgentState:
    state["steps_log"].append("🧪 Validating result...")

    if state.get("sql_error"):
        state["validation_status"] = "error"
        state["steps_log"].append("⚠️ Validation failed — SQL had an error.")
        return state

    if not state.get("sql_result") or state["sql_result"].strip() == "":
        state["validation_status"] = "invalid"
        state["sql_error"] = "Query returned no results. Reconsider the query logic."
        state["steps_log"].append("⚠️ Query returned empty result — may need rewrite.")
        return state

    llm = get_llm()
    prompt = f"""You are validating whether a SQL query result correctly answers a user's question.

User question: {state['user_question']}

SQL query used:
{state['sql_query']}

Query result:
{state['sql_result']}

Does this result look like a correct and meaningful answer to the question?
Reply with ONLY one word: YES or NO. Nothing else."""

    response = llm.invoke(prompt)
    answer = response.content.strip().upper()

    if "YES" in answer:
        state["validation_status"] = "valid"
        state["steps_log"].append("✅ Result validated successfully.")
    else:
        state["validation_status"] = "invalid"
        state["sql_error"] = "Result did not seem to correctly answer the question."
        state["steps_log"].append("⚠️ Result seems incorrect — retrying...")

    return state

# This node takes the validated SQL result and generates a natural language answer to the user's question, highlighting key insights.
# ── Node 5: Answer Explainer ──────────────────────────────────────────────────
def answer_explainer_node(state: AgentState) -> AgentState:
    state["steps_log"].append("💬 Generating natural language answer...")

    llm = get_llm()
    prompt = f"""You are a data analyst explaining query results to a business user.

User question: {state['user_question']}

SQL query used:
{state['sql_query']}

Query result:
{state['sql_result']}

Write a clear, concise answer in 2-4 sentences. Highlight the key numbers or findings.
Do not mention SQL or technical details — just explain the insight."""

    response = llm.invoke(prompt)
    state["final_answer"] = response.content.strip()
    state["steps_log"].append("✅ Done!")
    return state


# ── Routing logic ─────────────────────────────────────────────────────────────
def should_retry(state: AgentState) -> str:
    if state["validation_status"] == "valid":
        return "explain"
    if state["retry_count"] >= MAX_RETRIES:
        state["steps_log"].append("❌ Max retries reached.")
        state["final_answer"] = (
            f"I was unable to produce a correct query after {MAX_RETRIES} attempts.\n\n"
            f"Last SQL tried:\n{state['sql_query']}\n\n"
            f"Last error: {state.get('sql_error', 'Result looked incorrect')}"
        )
        return "end"
    state["retry_count"] += 1
    return "retry"